apiVersion: apps/v1
kind: Deployment
metadata:
  name: linksnap
  labels:
    app: linksnap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linksnap
  template:
    metadata:
      labels:
        app: linksnap
    spec:
      containers:
      - name: linksnap
        image: skamsani2023/linksnap:v1
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 30