replicaCount: 2

image:
  repository: skamsani2023/linksnap
  tag: "v1"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
  targetPort: 5000

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"